[host]
rustflags = [
    "--cfg", "anodized_print",
    "--cfg", "anodized_panic",
    "--cfg", "anodized_try",
]

[build]
rustflags = [
    "--cfg", "anodized_print",
    "--cfg", "anodized_panic",
    "--cfg", "anodized_try",
]
